# Generated by Django 6.0.2 on 2026-03-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_servicerequest_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='email',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='full_name',
        ),
        migrations.AlterField(
            model_name='servicerequest',
            name='status',
            field=models.CharField(choices=[('new', '🆕 Новая'), ('in_progress', '⚙️ В обработке'), ('completed', '✅ Завершена'), ('rejected', '❌ Отклонена'), ('reviewed', '👁️ Рассмотрено')], default='new', max_length=20, verbose_name='Статус'),
        ),
    ]
