# Generated by Django 6.0.2 on 2026-03-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_servicerequest_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=500, verbose_name='Адрес')),
                ('working_hours', models.CharField(blank=True, max_length=200, verbose_name='Часы работы')),
                ('map_link', models.URLField(blank=True, verbose_name='Ссылка на карту')),
                ('vk_link', models.URLField(blank=True, verbose_name='VK')),
                ('telegram_link', models.URLField(blank=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='SiteStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_experience', models.PositiveIntegerField(default=29, verbose_name='Лет опыта')),
                ('projects_completed', models.PositiveIntegerField(default=1300, verbose_name='Реализованных проектов')),
                ('federal_projects', models.PositiveIntegerField(default=520, verbose_name='Проектов федерального масштаба')),
                ('employees_count', models.PositiveIntegerField(default=120, verbose_name='Количество сотрудников')),
                ('regions_count', models.PositiveIntegerField(blank=True, default=50, null=True, verbose_name='Регионов присутствия')),
            ],
            options={
                'verbose_name': 'Статистика компании',
                'verbose_name_plural': 'Статистика компании',
            },
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
