# Generated by Django 6.0.2 on 2026-04-07 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_contactinfo_sitestatistics_delete_servicerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='О компании', max_length=200, verbose_name='Заголовок раздела')),
                ('text', models.TextField(verbose_name='Текст о компании')),
            ],
            options={
                'verbose_name': 'О компании',
                'verbose_name_plural': 'О компании',
            },
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='telegram_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='vk_link',
        ),
    ]
