# Generated by Django 6.0.2 on 2026-04-08 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_aboutinfo_remove_contactinfo_telegram_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinfo',
            name='map_link',
        ),
        migrations.RemoveField(
            model_name='contactinfo',
            name='working_hours',
        ),
    ]
