# Generated by Django 6.0.2 on 2026-04-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_remove_contactinfo_map_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmploymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='По вопросам трудоустройства', max_length=200, verbose_name='Заголовок блока')),
                ('person_name', models.CharField(max_length=200, verbose_name='Контактное лицо')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Трудоустройство',
                'verbose_name_plural': 'Трудоустройство',
            },
        ),
    ]
