# Generated by Django 6.0.2 on 2026-04-08 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_employmentinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmploymentInfo',
        ),
    ]
