# Generated by Django 6.0.2 on 2026-04-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_delete_employmentinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='sakhalin_address',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Адрес (Южно-Сахалинск)'),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='sakhalin_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон (Южно-Сахалинск)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='address',
            field=models.CharField(max_length=500, verbose_name='Адрес (Ростов-на-Дону)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email (Ростов-на-Дону)'),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Телефон (Ростов-на-Дону)'),
        ),
    ]
