# Generated by Django 6.0.2 on 2026-04-27 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_contactinfo_sakhalin_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='regions_count',
        ),
    ]
