# Generated by Django 6.0.2 on 2026-04-27 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_sitestatistics_regions_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitestatistics',
            name='federal_projects',
        ),
        migrations.AlterField(
            model_name='sitestatistics',
            name='projects_completed',
            field=models.PositiveIntegerField(default=1300, verbose_name='Проектов федерального масштаба'),
        ),
    ]
