"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""


from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-tlz4yj_^wi#&k1lpk!^9i51wvi-ot%&*=te0!h+g88y_d*9)d^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['dongis.tech', '192.168.0.186', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',  # оставляем для админки, но не используем на сайте
    'django.contrib.contenttypes',
    'django.contrib.sessions',  # оставляем для совместимости
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mainapp',
    'cookie_consent',
    'analytical'
]


YANDEX_METRICA_COUNTER_ID = '108990635'  


YANDEX_METRICA_WEBVISOR = True  
YANDEX_METRICA_CLICKMAP = True  
YANDEX_METRICA_TRACK_LINKS = True  
YANDEX_METRICA_ACCURATE_TRACK_BOUNCE = True  

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # добавляем общую папку шаблонов
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# settings.py
import mysql.connector

DATABASES = {
    'default': {
        'ENGINE': 'mysql.connector.django',
        'NAME': 'my_django_db',
        'USER': 'django_user',
        'PASSWORD': 'My@dmin2026!',
        'HOST': 'localhost',
        'PORT': '3306',
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
            'auth_plugin': 'mysql_native_password',  # Добавьте эту строку
        }
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
       'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
       'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'ru-ru'  # меняем на русский
TIME_ZONE = 'Europe/Moscow'  # меняем на свой часовой пояс
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'mainapp' / 'static',
]
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Email настройки для отправки заявок
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False

# Данные от почты, С КОТОРОЙ будут отправляться уведомления
EMAIL_HOST_USER = 'don.gis.bot.tech@gmail.com'  # Например: don-gis@yandex.ru
EMAIL_HOST_PASSWORD = 'eitlmpxlrancuzjt'  # Пароль приложения!

# Адресаты
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
SERVER_EMAIL = EMAIL_HOST_USER

# Администраторы, которые будут получать уведомления

ADMINS = [
    ('Администратор', 'viktoria.polkina006@gmail.com'),  
]

# Для mail_admins
MANAGERS = ADMINS

COOKIE_CONSENT_NAME = 'cookie_consent'
COOKIE_CONSENT_MAX_AGE = 365 * 24 * 60 * 60
COOKIE_CONSENT_LOG_ENABLED = False  
COOKIE_CONSENT_OPT_OUT = False

EMAIL_USE_LOCALTIME = True